# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 846)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.gridLayout_39 = QtWidgets.QGridLayout()
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.img1_original = ImageView(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img1_original.sizePolicy().hasHeightForWidth())
        self.img1_original.setSizePolicy(sizePolicy)
        self.img1_original.setMinimumSize(QtCore.QSize(0, 0))
        self.img1_original.setObjectName("img1_original")
        self.gridLayout_2.addWidget(self.img1_original, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.img1_updated = ImageView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img1_updated.sizePolicy().hasHeightForWidth())
        self.img1_updated.setSizePolicy(sizePolicy)
        self.img1_updated.setMinimumSize(QtCore.QSize(0, 0))
        self.img1_updated.setObjectName("img1_updated")
        self.gridLayout.addWidget(self.img1_updated, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_10, 2, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_img1 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_img1.setFont(font)
        self.label_img1.setStyleSheet("")
        self.label_img1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_img1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_img1.setObjectName("label_img1")
        self.gridLayout_16.addWidget(self.label_img1, 0, 0, 1, 1)
        self.combo_input1 = QtWidgets.QComboBox(self.groupBox)
        self.combo_input1.setEnabled(False)
        self.combo_input1.setMinimumSize(QtCore.QSize(200, 30))
        self.combo_input1.setAcceptDrops(False)
        self.combo_input1.setIconSize(QtCore.QSize(20, 20))
        self.combo_input1.setObjectName("combo_input1")
        self.combo_input1.addItem("")
        self.combo_input1.addItem("")
        self.combo_input1.addItem("")
        self.combo_input1.addItem("")
        self.combo_input1.addItem("")
        self.gridLayout_16.addWidget(self.combo_input1, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.gridLayout_38.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 1, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.img2_original = ImageView(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img2_original.sizePolicy().hasHeightForWidth())
        self.img2_original.setSizePolicy(sizePolicy)
        self.img2_original.setMinimumSize(QtCore.QSize(0, 0))
        self.img2_original.setObjectName("img2_original")
        self.gridLayout_5.addWidget(self.img2_original, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.img2_updated = ImageView(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img2_updated.sizePolicy().hasHeightForWidth())
        self.img2_updated.setSizePolicy(sizePolicy)
        self.img2_updated.setMinimumSize(QtCore.QSize(0, 0))
        self.img2_updated.setObjectName("img2_updated")
        self.gridLayout_6.addWidget(self.img2_updated, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_14, 2, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_img2 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_img2.setFont(font)
        self.label_img2.setStyleSheet("")
        self.label_img2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_img2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_img2.setObjectName("label_img2")
        self.gridLayout_19.addWidget(self.label_img2, 0, 0, 1, 1)
        self.combo_input2 = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_input2.setEnabled(False)
        self.combo_input2.setMinimumSize(QtCore.QSize(200, 30))
        self.combo_input2.setAcceptDrops(False)
        self.combo_input2.setIconSize(QtCore.QSize(20, 20))
        self.combo_input2.setObjectName("combo_input2")
        self.combo_input2.addItem("")
        self.combo_input2.addItem("")
        self.combo_input2.addItem("")
        self.combo_input2.addItem("")
        self.combo_input2.addItem("")
        self.gridLayout_19.addWidget(self.combo_input2, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.gridLayout_39.addLayout(self.gridLayout_38, 0, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_21.addWidget(self.label, 0, 0, 1, 1)
        self.combo_output = QtWidgets.QComboBox(self.groupBox_7)
        self.combo_output.setEnabled(False)
        self.combo_output.setMinimumSize(QtCore.QSize(30, 30))
        self.combo_output.setAcceptDrops(False)
        self.combo_output.setIconSize(QtCore.QSize(20, 20))
        self.combo_output.setObjectName("combo_output")
        self.combo_output.addItem("")
        self.combo_output.addItem("")
        self.gridLayout_21.addWidget(self.combo_output, 0, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_7)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_20.addWidget(self.line_3, 1, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_23.addItem(spacerItem, 0, 0, 1, 1)
        self.label_comp1 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_comp1.setFont(font)
        self.label_comp1.setObjectName("label_comp1")
        self.gridLayout_23.addWidget(self.label_comp1, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_34.addItem(spacerItem2, 0, 0, 1, 1)
        self.combo_select_img1 = QtWidgets.QComboBox(self.groupBox_7)
        self.combo_select_img1.setEnabled(False)
        self.combo_select_img1.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_select_img1.setAcceptDrops(False)
        self.combo_select_img1.setIconSize(QtCore.QSize(20, 20))
        self.combo_select_img1.setObjectName("combo_select_img1")
        self.combo_select_img1.addItem("")
        self.combo_select_img1.addItem("")
        self.gridLayout_34.addWidget(self.combo_select_img1, 1, 0, 1, 1)
        self.gridLayout_33.addLayout(self.gridLayout_34, 0, 0, 1, 1)
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_36.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_37 = QtWidgets.QGridLayout()
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_37.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_37.addItem(spacerItem4, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_37.addWidget(self.label_7, 0, 2, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_37, 1, 0, 1, 1)
        self.slider_comp1 = QtWidgets.QSlider(self.groupBox_7)
        self.slider_comp1.setEnabled(False)
        self.slider_comp1.setMaximum(100)
        self.slider_comp1.setSingleStep(10)
        self.slider_comp1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_comp1.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_comp1.setObjectName("slider_comp1")
        self.gridLayout_36.addWidget(self.slider_comp1, 3, 0, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_36, 0, 0, 1, 1)
        self.gridLayout_33.addLayout(self.gridLayout_35, 0, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_33, 0, 0, 1, 1)
        self.combo_select_mode1 = QtWidgets.QComboBox(self.groupBox_7)
        self.combo_select_mode1.setEnabled(False)
        self.combo_select_mode1.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_select_mode1.setAcceptDrops(False)
        self.combo_select_mode1.setIconSize(QtCore.QSize(20, 20))
        self.combo_select_mode1.setObjectName("combo_select_mode1")
        self.combo_select_mode1.addItem("")
        self.combo_select_mode1.addItem("")
        self.combo_select_mode1.addItem("")
        self.combo_select_mode1.addItem("")
        self.combo_select_mode1.addItem("")
        self.combo_select_mode1.addItem("")
        self.combo_select_mode1.addItem("")
        self.gridLayout_32.addWidget(self.combo_select_mode1, 1, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_32, 0, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_22, 2, 0, 1, 1)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_25.addItem(spacerItem5, 0, 0, 1, 1)
        self.label_comp2 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_comp2.setFont(font)
        self.label_comp2.setObjectName("label_comp2")
        self.gridLayout_25.addWidget(self.label_comp2, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem6, 2, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_28.addItem(spacerItem7, 0, 0, 1, 1)
        self.combo_select_img2 = QtWidgets.QComboBox(self.groupBox_7)
        self.combo_select_img2.setEnabled(False)
        self.combo_select_img2.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_select_img2.setAcceptDrops(False)
        self.combo_select_img2.setIconSize(QtCore.QSize(20, 20))
        self.combo_select_img2.setObjectName("combo_select_img2")
        self.combo_select_img2.addItem("")
        self.combo_select_img2.addItem("")
        self.gridLayout_28.addWidget(self.combo_select_img2, 1, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_28, 0, 0, 1, 1)
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem8, 0, 0, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_31.addWidget(self.label_8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem9, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_31.addWidget(self.label_9, 0, 2, 1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_31, 1, 0, 1, 1)
        self.slider_comp2 = QtWidgets.QSlider(self.groupBox_7)
        self.slider_comp2.setEnabled(False)
        self.slider_comp2.setMaximum(100)
        self.slider_comp2.setSingleStep(10)
        self.slider_comp2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_comp2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_comp2.setObjectName("slider_comp2")
        self.gridLayout_30.addWidget(self.slider_comp2, 2, 0, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_29, 0, 1, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_27, 0, 0, 1, 1)
        self.combo_select_mode2 = QtWidgets.QComboBox(self.groupBox_7)
        self.combo_select_mode2.setEnabled(False)
        self.combo_select_mode2.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_select_mode2.setAcceptDrops(False)
        self.combo_select_mode2.setIconSize(QtCore.QSize(20, 20))
        self.combo_select_mode2.setObjectName("combo_select_mode2")
        self.combo_select_mode2.addItem("")
        self.combo_select_mode2.addItem("")
        self.combo_select_mode2.addItem("")
        self.combo_select_mode2.addItem("")
        self.combo_select_mode2.addItem("")
        self.combo_select_mode2.addItem("")
        self.combo_select_mode2.addItem("")
        self.gridLayout_26.addWidget(self.combo_select_mode2, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_26, 0, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_24, 4, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem10, 3, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_output1 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_output1.setFont(font)
        self.label_output1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_output1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_output1.setObjectName("label_output1")
        self.gridLayout_13.addWidget(self.label_output1, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.output_img1 = ImageView(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_img1.sizePolicy().hasHeightForWidth())
        self.output_img1.setSizePolicy(sizePolicy)
        self.output_img1.setMinimumSize(QtCore.QSize(0, 0))
        self.output_img1.setObjectName("output_img1")
        self.gridLayout_17.addWidget(self.output_img1, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_output2 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_output2.setFont(font)
        self.label_output2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_output2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_output2.setObjectName("label_output2")
        self.gridLayout_15.addWidget(self.label_output2, 0, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.output_img2 = ImageView(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_img2.sizePolicy().hasHeightForWidth())
        self.output_img2.setSizePolicy(sizePolicy)
        self.output_img2.setMinimumSize(QtCore.QSize(0, 0))
        self.output_img2.setObjectName("output_img2")
        self.gridLayout_18.addWidget(self.output_img2, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_15, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem11, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem12, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_10, 1, 0, 1, 1)
        self.gridLayout_39.addLayout(self.gridLayout_9, 0, 1, 1, 1)
        self.gridLayout_40.addLayout(self.gridLayout_39, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 26))
        self.menubar.setObjectName("menubar")
        self.menuLoad = QtWidgets.QMenu(self.menubar)
        self.menuLoad.setObjectName("menuLoad")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImage1 = QtWidgets.QAction(MainWindow)
        self.actionImage1.setObjectName("actionImage1")
        self.actionImage2 = QtWidgets.QAction(MainWindow)
        self.actionImage2.setObjectName("actionImage2")
        self.menuLoad.addAction(self.actionImage1)
        self.menuLoad.addAction(self.actionImage2)
        self.menubar.addAction(self.menuLoad.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Original Image"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Updated Image"))
        self.label_img1.setText(_translate("MainWindow", "Image 1"))
        self.combo_input1.setItemText(0, _translate("MainWindow", "Choose FT Component"))
        self.combo_input1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.combo_input1.setItemText(2, _translate("MainWindow", "Phase"))
        self.combo_input1.setItemText(3, _translate("MainWindow", "Real"))
        self.combo_input1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Original Image"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Updated Image"))
        self.label_img2.setText(_translate("MainWindow", "Image 2"))
        self.combo_input2.setItemText(0, _translate("MainWindow", "Choose FT Component"))
        self.combo_input2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.combo_input2.setItemText(2, _translate("MainWindow", "Phase"))
        self.combo_input2.setItemText(3, _translate("MainWindow", "Real"))
        self.combo_input2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.label.setText(_translate("MainWindow", "Mixer Output to:"))
        self.combo_output.setItemText(0, _translate("MainWindow", "Output1"))
        self.combo_output.setItemText(1, _translate("MainWindow", "Output2"))
        self.label_comp1.setText(_translate("MainWindow", "Component 1:"))
        self.combo_select_img1.setItemText(0, _translate("MainWindow", "Image1"))
        self.combo_select_img1.setItemText(1, _translate("MainWindow", "Image2"))
        self.label_6.setText(_translate("MainWindow", "0%"))
        self.label_7.setText(_translate("MainWindow", "100%"))
        self.combo_select_mode1.setItemText(0, _translate("MainWindow", "Choose Component"))
        self.combo_select_mode1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.combo_select_mode1.setItemText(2, _translate("MainWindow", "Phase"))
        self.combo_select_mode1.setItemText(3, _translate("MainWindow", "Real"))
        self.combo_select_mode1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.combo_select_mode1.setItemText(5, _translate("MainWindow", "Uniform Magnitude"))
        self.combo_select_mode1.setItemText(6, _translate("MainWindow", "Uniform Phase"))
        self.label_comp2.setText(_translate("MainWindow", "Component 2:"))
        self.combo_select_img2.setItemText(0, _translate("MainWindow", "Image1"))
        self.combo_select_img2.setItemText(1, _translate("MainWindow", "Image2"))
        self.label_8.setText(_translate("MainWindow", "0%"))
        self.label_9.setText(_translate("MainWindow", "100%"))
        self.combo_select_mode2.setItemText(0, _translate("MainWindow", "Choose Component"))
        self.combo_select_mode2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.combo_select_mode2.setItemText(2, _translate("MainWindow", "Phase"))
        self.combo_select_mode2.setItemText(3, _translate("MainWindow", "Real"))
        self.combo_select_mode2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.combo_select_mode2.setItemText(5, _translate("MainWindow", "Uniform Magnitude"))
        self.combo_select_mode2.setItemText(6, _translate("MainWindow", "Uniform Phase"))
        self.label_output1.setText(_translate("MainWindow", "Output 1"))
        self.label_output2.setText(_translate("MainWindow", "Output 2"))
        self.menuLoad.setTitle(_translate("MainWindow", "Load"))
        self.actionImage1.setText(_translate("MainWindow", "Image1"))
        self.actionImage2.setText(_translate("MainWindow", "Image2"))

from pyqtgraph import ImageView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

